In [56]:
import numpy as np
import pandas as p
import matplotlib.pyplot as plt

In [57]:
Data = p.read_csv('../data/bestsellers.csv')
dataset = Data
dataset

,Name,Author,User Rating,Reviews,Price,Year,Genre
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350.0,8.0,2016,Non Fiction
1,11/22/63: A Novel,Stephen King,4.6,2052.0,22.0,2011,Fiction
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979.0,15.0,2018,Non Fiction
3,1984 (Signet Classics),George Orwell,4.7,21424.0,6.0,2017,Fiction
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665.0,12.0,2019,Non Fiction
...,...,...,...,...,...,...,...
545,Wrecking Ball (Diary of a Wimpy Kid Book 14),Jeff Kinney,4.9,9413.0,8.0,2019,Fiction
546,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331.0,8.0,2016,Non Fiction
547,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331.0,8.0,2017,Non Fiction
548,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331.0,8.0,2018,Non Fiction
549,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331.0,8.0,2019,Non Fiction

In [58]:
dataset.dtypes

Name               str
Author             str
User Rating    float64
Reviews        float64
Price          float64
Year             int64
Genre              str
dtype: object

In [59]:
dataset.columns

Index(['Name', 'Author', 'User Rating', 'Reviews', 'Price', 'Year', 'Genre'], dtype='str')

In [60]:
dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 550 entries, 0 to 549
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Name         550 non-null    str
 1   Author       550 non-null    str
 2   User Rating  548 non-null    float64
 3   Reviews      549 non-null    float64
 4   Price        549 non-null    float64
 5   Year         550 non-null    int64
 6   Genre        550 non-null    str
dtypes: float64(3), int64(1), str(3)
memory usage: 30.2 KB

In [61]:
dataset.describe()

       User Rating       Reviews       Price         Year
count   548.000000    549.000000  549.000000   550.000000
mean      4.618066  11958.038251   13.100182  2014.000000
std       0.227341  11741.299889   10.852149     3.165156
min       3.300000     37.000000    0.000000  2009.000000
25%       4.500000   4028.000000    7.000000  2011.000000
50%       4.700000   8580.000000   11.000000  2014.000000
75%       4.800000  17323.000000   16.000000  2017.000000
max       4.900000  87841.000000  105.000000  2019.000000

In [62]:
dataset.isnull().sum()

Name           0
Author         0
User Rating    2
Reviews        1
Price          1
Year           0
Genre          0
dtype: int64

In [63]:
dataset.duplicated().sum()

np.int64(0)

In [64]:
dataset
x=dataset.iloc[:, :-1].values
x

array([['10-Day Green Smoothie Cleanse', 'JJ Smith', 4.7, 17350.0, 8.0,
        2016],
       ['11/22/63: A Novel', 'Stephen King', 4.6, 2052.0, 22.0, 2011],
       ['12 Rules for Life: An Antidote to Chaos', 'Jordan B. Peterson',
        4.7, 18979.0, 15.0, 2018],
       ...,
       ['You Are a Badass: How to Stop Doubting Your Greatness and Start Living an Awesome Life',
        'Jen Sincero', 4.7, 14331.0, 8.0, 2017],
       ['You Are a Badass: How to Stop Doubting Your Greatness and Start Living an Awesome Life',
        'Jen Sincero', 4.7, 14331.0, 8.0, 2018],
       ['You Are a Badass: How to Stop Doubting Your Greatness and Start Living an Awesome Life',
        'Jen Sincero', 4.7, 14331.0, 8.0, 2019]],
      shape=(550, 6), dtype=object)

In [65]:
y = dataset.iloc[:, 3].values
y

array([1.7350e+04, 2.0520e+03, 1.8979e+04, 2.1424e+04, 7.6650e+03,
       1.2643e+04, 1.9735e+04, 1.9699e+04, 5.9830e+03, 2.3848e+04,
       2.3848e+04, 4.6000e+02, 4.1490e+03, 5.1530e+03, 5.0130e+03,
       2.3130e+03, 2.9250e+03, 2.9510e+03, 2.4260e+03, 9.1980e+03,
       3.6348e+04, 3.6348e+04, 6.3100e+03, 1.5921e+04, 1.2159e+04,
       7.9800e+02, 9.3740e+03, 4.9100e+02, 5.3600e+03, 1.9090e+03,
       1.2960e+03, 6.1500e+02, 6.1133e+04, 6.1133e+04, 1.1113e+04,
       1.0070e+04, 1.0070e+04, 3.7290e+03, 9.7690e+03, 4.7100e+02,
       1.4344e+04, 1.4344e+04, 4.5050e+03, 1.0369e+04, 1.6244e+04,
       2.8840e+03, 2.2614e+04, 2.2614e+04, 2.2614e+04, 4.7610e+03,
       1.5420e+03, 1.5420e+03, 1.5420e+03, 6.1430e+03, 4.0220e+03,
       3.8710e+03, 4.8660e+03, 4.8660e+03, 1.3290e+03, 4.6420e+03,
       1.5410e+03, 1.9240e+03, 2.0940e+03, 1.0922e+04, 1.0922e+04,
       1.0922e+04, 1.0922e+04, 2.1370e+03, 1.6510e+03, 6.6790e+03,
       6.6790e+03, 6.8120e+03, 3.8370e+03, 6.5400e+03, 7.9550e+03,
       2.7098e+04, 2.7098e+04, 1.7684e+04, 3.7000e+01, 1.5845e+04,
       3.1810e+03, 5.0620e+03, 4.7860e+03, 7.2350e+03, 7.2350e+03,
       1.2619e+04, 9.0890e+03, 5.4700e+03, 5.1180e+03, 2.1340e+03,
       2.5250e+03, 7.2000e+02, 9.5600e+02, 6.3460e+03, 6.3460e+03,
       5.5050e+03, 5.5050e+03, 2.8729e+04, 2.8729e+04, 5.4130e+03,
       1.0721e+04, 1.0721e+04, 4.3700e+03, 6.0420e+03, 2.3631e+04,
       2.0262e+04, 4.7265e+04, 4.7265e+04, 1.3964e+04, 1.3677e+04,
       1.7323e+04, 1.7323e+04, 1.7323e+04, 1.7323e+04, 1.7323e+04,
       1.5550e+03, 3.6420e+03, 1.2150e+03, 5.5940e+03, 5.5940e+03,
       5.5940e+03, 4.0800e+02, 4.7990e+03, 1.4038e+04, 1.4038e+04,
       1.4038e+04, 1.4038e+04, 1.4038e+04, 7.6600e+03, 2.2288e+04,
       2.2288e+04, 1.3650e+03, 1.4982e+04, 9.5680e+03, 1.6360e+03,
       5.7271e+04, 5.7271e+04, 5.7271e+04, 1.0141e+04, 3.4570e+03,
       3.4570e+03, 3.4570e+03, 3.4570e+03, 8.8370e+03, 8.8370e+03,
       8.8370e+03, 7.0380e+03, 7.0380e+03, 5.9720e+03, 2.5624e+04,
       5.4760e+03, 5.8670e+03, 4.1480e+03, 1.9622e+04, 2.3973e+04,
       7.7580e+03, 3.1460e+03, 1.0052e+04, 3.5640e+03, 1.3471e+04,
       1.9300e+03, 1.5779e+04, 1.5779e+04, 1.5526e+04, 1.5526e+04,
       3.7760e+03, 2.5001e+04, 2.5001e+04, 2.5001e+04, 2.5001e+04,
       2.5001e+04, 5.2720e+03, 3.4900e+03, 3.4900e+03, 2.8120e+03,
       4.8960e+03, 9.7370e+03, 1.3200e+03, 1.6643e+04, 1.6643e+04,
       7.1530e+03, 4.5710e+03, 2.9651e+04, 5.2990e+03, 7.3960e+03,
       7.3960e+03, 7.0620e+03, 1.9576e+04, 1.9576e+04, 1.9576e+04,
       1.9576e+04, 1.9576e+04, 1.9576e+04, 9.7800e+02, 4.7480e+03,
       8.3930e+03, 1.1391e+04, 8.6340e+03,        nan, 9.3420e+03,
       1.0927e+04, 5.2350e+03, 8.9160e+03, 2.5070e+03, 3.6730e+03,
       3.6730e+03, 3.6730e+03, 1.1881e+04, 6.9900e+03, 6.9900e+03,
       6.9900e+03, 6.9900e+03, 6.9900e+03, 6.1320e+03, 3.0140e+03,
       7.5500e+03, 3.8280e+03, 2.7520e+03, 1.4670e+03, 1.8840e+03,
       2.5706e+04, 8.4910e+03, 1.6490e+03, 1.8613e+04, 1.8613e+04,
       9.8670e+03, 1.3860e+03, 1.0199e+04, 2.9260e+03, 1.7739e+04,
       1.7739e+04, 1.7739e+04, 3.1130e+03, 5.5420e+03, 5.5420e+03,
       5.5420e+03, 2.6741e+04, 2.6741e+04, 2.6741e+04, 5.3470e+03,
       7.8660e+03, 5.6800e+03, 5.1780e+03, 8.0930e+03, 3.1920e+03,
       2.1834e+04, 2.1834e+04, 2.1834e+04, 2.1834e+04, 2.1834e+04,
       2.1834e+04, 2.1834e+04, 2.1834e+04, 6.1690e+03, 4.5190e+03,
       3.1630e+03, 3.1630e+03, 1.8310e+03, 1.8904e+04, 2.1930e+04,
       1.0426e+04, 1.0426e+04, 1.0820e+04, 1.0820e+04, 5.4800e+02,
       1.6990e+04, 1.6990e+04, 1.6990e+04, 3.5030e+03, 1.3616e+04,
       1.3616e+04, 8.5800e+03, 8.5800e+03, 8.5800e+03, 8.5800e+03,
       8.5800e+03, 8.5800e+03, 8.5800e+03, 8.5800e+03, 8.5800e+03,
       8.5800e+03, 4.7570e+03, 1.0009e+04, 1.0009e+04, 1.9850e+03,
       1.9850e+03, 2.2536e+04, 2.2536e+04, 7.1500e+03, 3.8360e+03,
       7.8020e+03, 7.8020e+03, 3.6190e+03, 2.3047e+04, 2.3047e+04,
       9.3660e+03, 1.2650e+03, 3.9230e+03, 2.2720e+03, 9.7300e+02,
       2.2000e+02, 7.8270e+03, 7.8270e+03, 9.3820e+03, 5.0690e+03,
       5.0690e+03, 5.0690e+03, 5.0690e+03, 5.0690e+03, 5.0690e+03,
       5.0690e+03, 5.0690e+03, 5.0690e+03, 1.5830e+03, 1.9070e+03,
       2.3114e+04, 6.3700e+02, 6.3700e+02, 2.3140e+03, 4.5870e+03,
       3.4770e+03, 3.4770e+03, 3.4770e+03, 3.4770e+03, 3.4770e+03,
       2.5554e+04, 2.5554e+04, 2.5554e+04, 2.5554e+04, 2.5554e+04,
       1.6800e+03, 9.3250e+03, 9.3250e+03, 9.3250e+03, 9.3250e+03,
       4.7250e+03, 4.7250e+03, 4.7250e+03, 3.5799e+04, 2.5800e+03,
       1.1813e+04, 1.1813e+04, 3.5360e+03, 6.6000e+03, 1.7890e+03,
       1.2361e+04, 8.5800e+02, 2.3148e+04, 2.3148e+04, 8.0810e+03,
       8.0810e+03, 2.3358e+04, 2.3358e+04, 9.3720e+03, 4.6330e+03,
       1.3061e+04, 1.3061e+04, 3.5230e+03, 2.7740e+03, 4.4000e+02,
       8.9220e+03, 8.9220e+03, 8.9220e+03, 2.0230e+03, 1.8590e+03,
       5.0482e+04, 5.0482e+04, 5.0482e+04, 5.0482e+04, 3.2070e+03,
       3.2070e+03, 3.2070e+03, 3.2070e+03, 3.2070e+03, 8.0300e+02,
       2.3308e+04, 2.3308e+04, 2.3308e+04, 2.3308e+04, 2.3308e+04,
       2.3308e+04, 5.8360e+03, 7.9446e+04, 7.9446e+04, 7.7470e+03,
       7.7470e+03, 7.2510e+03, 7.2510e+03, 1.0559e+04, 1.0559e+04,
       5.2490e+03, 5.2490e+03, 3.3844e+04, 3.3844e+04, 1.1616e+04,
       1.1616e+04, 1.1616e+04, 1.3609e+04, 8.5870e+03, 2.9442e+04,
       1.1098e+04, 9.9470e+03, 1.3871e+04, 1.3871e+04, 1.3871e+04,
       1.3871e+04, 6.9820e+03, 3.2122e+04, 3.2122e+04, 3.2122e+04,
       1.6949e+04, 1.6949e+04, 9.2890e+03, 9.2890e+03, 9.2890e+03,
       7.3680e+03, 7.3680e+03, 4.0280e+03, 4.6280e+03, 4.6280e+03,
       5.3960e+03, 4.2470e+03, 4.2470e+03, 2.2641e+04, 2.2641e+04,
       2.2641e+04, 2.2641e+04, 6.2220e+03, 4.5060e+03, 8.7470e+03,
       1.6550e+03, 7.8610e+03, 6.2470e+03, 3.9459e+04, 1.0101e+04,
       5.8980e+03, 2.7440e+03, 4.9288e+04, 4.9288e+04, 1.2010e+03,
       1.2010e+03, 1.2010e+03, 1.2010e+03, 1.2010e+03, 8.0700e+02,
       3.7590e+03, 2.6630e+03, 3.4280e+03, 2.8760e+03, 3.6010e+03,
       7.0580e+03, 9.7840e+03, 9.7840e+03, 1.0795e+04, 1.0191e+04,
       1.4493e+04, 2.1860e+03, 1.2040e+03, 2.0910e+03, 1.9720e+04,
       1.9720e+04, 2.1220e+03, 2.7536e+04, 4.2900e+03, 2.6490e+04,
       2.6490e+04, 2.6490e+04, 5.4870e+03, 6.3770e+03, 1.4630e+03,
       3.7590e+03, 3.5030e+03, 1.1550e+04, 3.8010e+03, 3.7960e+03,
       9.0300e+03, 1.9546e+04, 1.9546e+04, 1.9546e+04, 1.9546e+04,
       1.9546e+04, 1.9546e+04, 1.9546e+04, 7.5080e+03, 7.5080e+03,
       7.5080e+03, 8.8420e+03, 8.8420e+03, 8.8420e+03, 8.8420e+03,
       3.0183e+04, 3.0183e+04, 6.1690e+03, 7.0340e+03, 1.1034e+04,
       1.1034e+04, 7.9320e+03, 1.9040e+03, 3.3190e+03, 3.3190e+03,
       1.1128e+04, 1.1128e+04, 1.1128e+04, 1.1128e+04, 5.9770e+03,
       2.6234e+04, 2.6234e+04, 2.6234e+04, 2.6234e+04, 2.6234e+04,
       4.3600e+03, 2.2820e+03, 4.3800e+02, 1.1676e+04, 2.5860e+03,
       2.9673e+04, 2.9673e+04, 2.9673e+04, 2.9673e+04, 2.9673e+04,
       6.7400e+03, 5.9560e+03, 6.1080e+03, 4.5850e+03, 3.8290e+03,
       8.9580e+03, 5.4920e+03, 9.2920e+03, 1.8730e+03, 8.1700e+03,
       3.3410e+03, 7.4970e+03, 7.4970e+03, 1.3779e+04, 8.7841e+04,
       9.9670e+03, 6.6690e+03, 1.7044e+04, 1.0760e+04, 1.3020e+03,
       2.1625e+04, 2.1625e+04, 2.1625e+04, 2.1625e+04, 2.1625e+04,
       9.4130e+03, 1.4331e+04, 1.4331e+04, 1.4331e+04, 1.4331e+04])

In [66]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(missing_values=np.nan, strategy='mean')

imputer = imputer.fit(x[:, 2:6])
x[:, 2:6] = imputer.transform(x[:, 2:6])

x

array([['10-Day Green Smoothie Cleanse', 'JJ Smith', 4.7, 17350.0, 8.0,
        2016.0],
       ['11/22/63: A Novel', 'Stephen King', 4.6, 2052.0, 22.0, 2011.0],
       ['12 Rules for Life: An Antidote to Chaos', 'Jordan B. Peterson',
        4.7, 18979.0, 15.0, 2018.0],
       ...,
       ['You Are a Badass: How to Stop Doubting Your Greatness and Start Living an Awesome Life',
        'Jen Sincero', 4.7, 14331.0, 8.0, 2017.0],
       ['You Are a Badass: How to Stop Doubting Your Greatness and Start Living an Awesome Life',
        'Jen Sincero', 4.7, 14331.0, 8.0, 2018.0],
       ['You Are a Badass: How to Stop Doubting Your Greatness and Start Living an Awesome Life',
        'Jen Sincero', 4.7, 14331.0, 8.0, 2019.0]],
      shape=(550, 6), dtype=object)

In [67]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_x = LabelEncoder()
x[:, 0] = labelencoder_x.fit_transform(x[:, 0])
print(x)

[[0 'JJ Smith' 4.7 17350.0 8.0 2016.0]
 [1 'Stephen King' 4.6 2052.0 22.0 2011.0]
 [2 'Jordan B. Peterson' 4.7 18979.0 15.0 2018.0]
 ...
 [350 'Jen Sincero' 4.7 14331.0 8.0 2017.0]
 [350 'Jen Sincero' 4.7 14331.0 8.0 2018.0]
 [350 'Jen Sincero' 4.7 14331.0 8.0 2019.0]]

In [68]:
labelenc_y = LabelEncoder()
y = labelenc_y.fit_transform(y)
y

array([291,  52, 296, 304, 196, 267, 302, 300, 163, 318, 318,   5, 113,
       139, 135,  61,  75,  77,  63, 221, 337, 337, 171, 284, 264,  12,
       228,   7, 146,  47,  23,   9, 343, 343, 256, 240, 240,  99, 233,
         6, 278, 278, 118, 245, 285,  74, 310, 310, 310, 130,  32,  32,
        32, 167, 110, 108, 133, 133,  26, 126,  31,  48,  54, 252, 252,
       252, 252,  57,  37, 177, 177, 179, 107, 174, 204, 327, 327, 292,
         0, 283,  82, 136, 131, 188, 188, 266, 220, 149, 138,  56,  65,
        11,  16, 172, 172, 153, 153, 329, 329, 148, 248, 248, 117, 164,
       317, 303, 339, 339, 275, 272, 290, 290, 290, 290, 290,  33,  97,
        21, 155, 155, 155,   2, 132, 276, 276, 276, 276, 276, 195, 308,
       308,  27, 280, 231,  35, 342, 342, 342, 242,  88,  88,  88,  88,
       214, 214, 214, 183, 183, 161, 322, 150, 158, 112, 299, 319, 198,
        80, 239,  94, 269,  49, 282, 282, 281, 281, 101, 320, 320, 320,
       320, 320, 143,  90,  90,  72, 134, 232,  25, 286, 286, 187, 121,
       331, 144, 191, 191, 185, 298, 298, 298, 298, 298, 298,  18, 128,
       208, 258, 212, 346, 225, 253, 141, 216,  64,  98,  98,  98, 263,
       181, 181, 181, 181, 181, 166,  78, 194, 104,  70,  30,  44, 323,
       209,  36, 294, 294, 235,  28, 244,  76, 293, 293, 293,  79, 154,
       154, 154, 326, 326, 326, 145, 202, 156, 140, 206,  83, 306, 306,
       306, 306, 306, 306, 306, 306, 168, 120,  81,  81,  41, 295, 307,
       246, 246, 251, 251,   8, 288, 288, 288,  91, 271, 271, 210, 210,
       210, 210, 210, 210, 210, 210, 210, 210, 129, 238, 238,  50,  50,
       309, 309, 186, 106, 199, 199,  96, 312, 312, 226,  22, 109,  59,
        17,   1, 200, 200, 229, 137, 137, 137, 137, 137, 137, 137, 137,
       137,  34,  46, 313,  10,  10,  62, 123,  89,  89,  89,  89,  89,
       321, 321, 321, 321, 321,  39, 224, 224, 224, 224, 127, 127, 127,
       336,  66, 262, 262,  93, 175,  40, 265,  15, 314, 314, 205, 205,
       316, 316, 227, 125, 268, 268,  92,  71,   4, 217, 217, 217,  51,
        42, 341, 341, 341, 341,  84,  84,  84,  84,  84,  13, 315, 315,
       315, 315, 315, 315, 157, 344, 344, 197, 197, 189, 189, 247, 247,
       142, 142, 335, 335, 260, 260, 260, 270, 211, 330, 255, 236, 274,
       274, 274, 274, 180, 334, 334, 334, 287, 287, 222, 222, 222, 190,
       190, 111, 124, 124, 147, 114, 114, 311, 311, 311, 311, 169, 119,
       213,  38, 201, 170, 338, 241, 159,  69, 340, 340,  19,  19,  19,
        19,  19,  14, 100,  68,  87,  73,  95, 184, 234, 234, 250, 243,
       279,  58,  20,  53, 301, 301,  55, 328, 115, 325, 325, 325, 151,
       173,  29, 100,  91, 259, 103, 102, 219, 297, 297, 297, 297, 297,
       297, 297, 193, 193, 193, 215, 215, 215, 215, 333, 333, 168, 182,
       254, 254, 203,  45,  85,  85, 257, 257, 257, 257, 162, 324, 324,
       324, 324, 324, 116,  60,   3, 261,  67, 332, 332, 332, 332, 332,
       178, 160, 165, 122, 105, 218, 152, 223,  43, 207,  86, 192, 192,
       273, 345, 237, 176, 289, 249,  24, 305, 305, 305, 305, 305, 230,
       277, 277, 277, 277])

In [71]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(
    transformers=[
        ("categorical", OneHotEncoder(handle_unknown="ignore", sparse_output=False), [0, 1, 5])
    ],
    remainder="passthrough"
)

x = ct.fit_transform(x)

x

array([[1.0, 0.0, 0.0, ..., 4.7, 17350.0, 8.0],
       [0.0, 1.0, 0.0, ..., 4.6, 2052.0, 22.0],
       [0.0, 0.0, 1.0, ..., 4.7, 18979.0, 15.0],
       ...,
       [0.0, 0.0, 0.0, ..., 4.7, 14331.0, 8.0],
       [0.0, 0.0, 0.0, ..., 4.7, 14331.0, 8.0],
       [0.0, 0.0, 0.0, ..., 4.7, 14331.0, 8.0]],
      shape=(550, 613), dtype=object)

In [72]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 45)

In [73]:
x_test

array([[0.0, 0.0, 0.0, ..., 4.6, 19720.0, 8.0],
       [0.0, 0.0, 0.0, ..., 4.8, 29673.0, 16.0],
       [0.0, 0.0, 0.0, ..., 4.7, 10820.0, 5.0],
       ...,
       [0.0, 0.0, 0.0, ..., 4.7, 6377.0, 7.0],
       [0.0, 0.0, 0.0, ..., 4.8, 2091.0, 12.0],
       [0.0, 0.0, 0.0, ..., 4.3, 5272.0, 16.0]],
      shape=(110, 613), dtype=object)

In [74]:
x_test.astype(int)

array([[    0,     0,     0, ...,     4, 19720,     8],
       [    0,     0,     0, ...,     4, 29673,    16],
       [    0,     0,     0, ...,     4, 10820,     5],
       ...,
       [    0,     0,     0, ...,     4,  6377,     7],
       [    0,     0,     0, ...,     4,  2091,    12],
       [    0,     0,     0, ...,     4,  5272,    16]], shape=(110, 613))

In [75]:
from sklearn.preprocessing import StandardScaler

sc_x = StandardScaler()

x_train = sc_x.fit_transform(x_train)
x_test = sc_x.transform(x_test)

In [ ]:
x_train.astype(int)

array([[-1,  0,  1, -1, -1],
       [-1,  2,  0,  1,  1],
       [ 1,  0,  0,  0,  0],
       [-1,  0,  1,  0, -1],
       [ 1,  0,  0,  0,  0],
       [ 1,  0,  0,  1,  1],
       [ 1,  0,  0,  0,  0],
       [-1,  0,  1,  0,  0]])

In [76]:
x_test.astype(int)

array([[ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  1,  0],
       [ 0,  0,  0, ...,  0,  0,  0],
       ...,
       [ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ..., -1,  0,  0]], shape=(110, 613))